name: Invite User to GitHub Org on labeled issue

on:
  issues:
    types: [labeled]

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite on label
        uses: vj-abigo/invite-on-label@v1.4
        with:
          organization: WildChickenUniversity
          label: apply-wcu
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: |
            Welcome to the Wild Chicken Univeristy!

            Note that we assume you read the [disclaimer](https://wcu.edu.pl/pages/disclaimer) carefully :)
          existingMemberMessage: "You are already an alumni, please DO NOT create multiple requests or else we will be forced to remove you."
        env:
          INVITE_TOKEN: ${{ secrets.INVITE_TOKEN }}
